module.exports = {
  content: ['./layouts/**/*.html', './content/**/*.md'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif', '"Apple Color Emoji"', '"Segoe UI Emoji"', '"Segoe UI Symbol"', '"Noto Color Emoji"'],
      },
      letterSpacing: {
        'heading': '-0.02em',
      },
      colors: {
        m: {
          primary: 'var(--m-primary)',
          'on-primary': 'var(--m-on-primary)',
          'primary-container': 'var(--m-primary-container)',
          'on-primary-container': 'var(--m-on-primary-container)',
          secondary: 'var(--m-secondary)',
          'on-secondary': 'var(--m-on-secondary)',
          'secondary-container': 'var(--m-secondary-container)',
          'on-secondary-container': 'var(--m-on-secondary-container)',
          tertiary: 'var(--m-tertiary)',
          'on-tertiary': 'var(--m-on-tertiary)',
          'tertiary-container': 'var(--m-tertiary-container)',
          'on-tertiary-container': 'var(--m-on-tertiary-container)',
          accent: 'var(--m-accent)',
          'on-accent': 'var(--m-on-accent)',
          'accent-container': 'var(--m-accent-container)',
          'on-accent-container': 'var(--m-on-accent-container)',
          warm: 'var(--m-warm)',
          'on-warm': 'var(--m-on-warm)',
          'warm-container': 'var(--m-warm-container)',
          'on-warm-container': 'var(--m-on-warm-container)',
          rose: 'var(--m-rose)',
          'on-rose': 'var(--m-on-rose)',
          'rose-container': 'var(--m-rose-container)',
          'on-rose-container': 'var(--m-on-rose-container)',
          surface: 'var(--m-surface)',
          'on-surface': 'var(--m-on-surface)',
          'on-surface-variant': 'var(--m-on-surface-variant)',
          'container-lowest': 'var(--m-container-lowest)',
          'container-low': 'var(--m-container-low)',
          container: 'var(--m-container)',
          'container-high': 'var(--m-container-high)',
          'container-highest': 'var(--m-container-highest)',
          outline: 'var(--m-outline)',
          note: 'var(--m-note)',
          'on-note': 'var(--m-on-note)',
        },
      },
    },
  },
  plugins: [],
}
