/* 2.4.0-G：编译期功能开关（Hugo js.Build define 注入，esbuild 替换为 true/false）。
   由 data/features.yaml 生成，保持同步。 */
declare const SGX_FEAT_THEME_MODE: boolean;
declare const SGX_FEAT_PALETTE: boolean;
declare const SGX_FEAT_FONT_SIZE: boolean;
declare const SGX_FEAT_LAYOUT: boolean;
declare const SGX_FEAT_LANG: boolean;
declare const SGX_FEAT_REDUCED_MOTION: boolean;
declare const SGX_FEAT_GL_WELLBEING: boolean;
declare const SGX_FEAT_GL_PARALLAX: boolean;
declare const SGX_FEAT_GL_CLOCKSTYLE: boolean;
declare const SGX_FEAT_GL_SOUND: boolean;
declare const SGX_FEAT_GL_KEYS: boolean;
declare const SGX_FEAT_GL_EDGEGLOW: boolean;
declare const SGX_FEAT_WEATHER_SHOW: boolean;
declare const SGX_FEAT_TEMP_UNIT: boolean;
declare const SGX_FEAT_TZ1_AUTO: boolean;
declare const SGX_FEAT_TZ1: boolean;
declare const SGX_FEAT_TZ2: boolean;
declare const SGX_FEAT_HOUR12: boolean;
declare const SGX_FEAT_SEARCH_ENGINE: boolean;
declare const SGX_FEAT_ADDRBAR_POS: boolean;
declare const SGX_FEAT_FILES_VIEW: boolean;
declare const SGX_FEAT_FILES_HOME: boolean;
declare const SGX_FEAT_APPS_HIDDEN: boolean;
declare const SGX_FEAT_WELL_TIP: boolean;
/* 2.8.0：SGX_FEAT_LEGACY_LOCK_SCREEN 已彻底删除 */
declare const SGX_FEAT_OWNER_GATE: boolean;
/* Hark：CI 测试构建期禁用锁屏（SGX_TEST_NO_LOCK=1 时）；生产构建为 false */
declare const SGX_TEST_NO_LOCK: boolean;
